### ISSUE TITLE
webhook-go.service runs as the root user

### ISSUE THREAD

**Issue by magarvo** [voxpupuli/webhook-go#138]
Hi,

The webhook-go.service runs under the 'root' user. It seems that it would be more secure that it runs under a different user.

I currently run it under the puppet user and all my keys and permissions are built around the puppet user. However that may create a dependency on the puppet-agent or puppetserver package.

https://github.com/voxpupuli/webhook-go/blob/master/build/webhook-go.service

**Comment by dhollinger** [comment]
Currently, switching the user shouldn't be a problem. This becomes a bit more tricky once we implement the ability to use webhook-go to remotely deploy updates to multiple puppet servers.

The other issue is if the puppet user would have enough permissions for all users to deploy wherever there environment and/or moduledir
