### ISSUE TITLE
Simple queuing mechanism needed

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/webhook-go#58]
I tried to use this project with webhooks from gitlab.com but ran into some blockers.

When gitlab posts a webhook it expects a speedy response.  The current implementation tries and waits for r10k [to execute](https://github.com/voxpupuli/webhook-go/blob/c03c8fa940255285e7233e7a7067114d0ed4f195/api/module.go#L65) before sending any response.

From the gitlab docs...
> "Your endpoint should send its HTTP response as fast as possible. You should aim for sub-second response times in all circumstances."

and

> "If a webhook fails repeatedly, it may be disabled automatically."

In my opinion it should just send a 202 as soon as it's parsed the webhook and queued the r10k work.

A related issue is that currently, the service will happily attempt to process multiple incoming webhooks concurrently. Running multiple instances of r10k simultaneously does not end well...

Before we can recommend users switch to this project, I think this needs to be solved.  I don't think we need to go crazy though by implementing sidekiq or redis etc.  Not sure what an equivalent go solution would look like, but in python I've seen really simple code used to [queue ](https://docs.python.org/3/library/queue.html) webhooks.  I'll try to get some pseudocode together to demonstrate.

**Comment by alexjfisher** [comment]
Here is some very cut down python code based on some real uwsgi run python code I use to process bitbucket (and recently also gitlab.com) webhooks and execute r10k from a single thread.  Treat as pseudocode as I've stripped out lots of detail (and probably added loads of bugs/syntax errors in the process!).
```python
environment_queue = Queue.Queue()
module_queue = Queue.Queue()

def qproc():
    global environment_queue,module_queue
    while True:
        try:
            envs = set()
            e = environment_queue.get(True,1) # Block for 1 second
            envs.add(e)

            # Minimise the number of calls to r10k we make, by grabbing any other pending environments off the queue too
            try:
                while not environment_queue.empty():
                    e = environment_queue.get_nowait()
                    envs.add(e)           
            except Queue.Empty:
                # We should never get here
                pass
            run_r10k('envs', envs)
        except Queue.Empty:
            pass

        # Now process any 'module' jobs
        mods = set()
        try:
            while not module_queue.empty():
                m = module_queue.get_nowait() # No need to block again here.
                mods.add(m)
        except Queue.Empty:
            pass
        if len(mods) > 0:
            run_r10k('modules', mods)

t = threading.Thread(target=qproc)
t.start()

def application(env, start_response):
    if env['PATH_INFO'] == '/module':
        return process_module_hook(env, start_response)
    elif env['PATH_INFO'] == '/environment':
        return process_environment_hook(env, start_response)
    elif env['PATH_INFO'] == '/health':
        start_response('200 OK', [('Content-Type','text/plain')])
        return [b'OK']
    else:
        start_response('400 Bad Request', [])
        return [b'']

def process_module_hook(env, start_response):
    try:
       module = PARSE_AND_EXTRACT_MODULE_FROM_WEBHOOK_HERE
       module_queue.put(module)
    start_response('200 OK', [('Content-Type','text/plain')])
        return [b'OK']
    except:
        traceback.print_exc()
        start_response('500 Internal Server Error', [('Content-Type','text/plain')])
        return [b'Internal server error'] 

# process_environment_hook and run_r10k functions omitted.
```

**Comment by ekohl** [comment]
I was thinking that there are some constraints.

First of all, only one process should run at the same time. This may be fairly obvious, but very important. A user may push another commit before the deployment completed and having 2 deployment processes running at the same time is asking for problems.

The next is more of an optimization. If you run a deployment, it will update to the latest version. Let's say the user pushed a commit, so deployment started. Now the user pushed another commit. Then another push. Deployment is still running, but there may also be 2 more deployments scheduled. However, the last won't have any changes. This means the queue depths is at most 1.

To get a simple queue I had thought about using systemd. So I defined a simple service
```console
$ systemctl cat --user puppet-code.service 
# /home/ekohl/.config/systemd/user/puppet-code.service
[Unit]
Description=Deploy puppet code

[Service]
Type=oneshot
ExecStart=%h/bin/puppet-code
$ cat ~/bin/puppet-code 
#!/bin/sh
sleep 10
date >> /tmp/puppet-code.log
```

Then I queued a few times:
```console
$ date ; for i in 1 2 3 4 5 ; do systemctl start --user --no-block puppet-code.service ; done ; date
Wed 14 Sep 11:46:45 CEST 2022
Wed 14 Sep 11:46:45 CEST 2022
$ sleep 25 ; cat /tmp/puppet-code.log 
begin: Wed 14 Sep 11:46:45 CEST 2022
end:   Wed 14 Sep 11:46:55 CEST 2022
```

Now you can see it only runs it once. That's good, but it also means that while it's running, it doesn't queue another item. So it loses some runs, which is bad.

So this is probably not the solution I was hoping for.

**Comment by ekohl** [comment]
Overall I like @alexjfisher's suggestion for its simplicity, but I think this may be a nice improvement.

```python
import subprocess
from queue import Empty, Queue
from threading import Lock, Thread

R10K_LOCK = Lock()
ENVIRONMENT_QUEUE = Queue()
MODULE_QUEUE = Queue()


def run_r10k(kind, values):
    global R10K_LOCK
    with R10K_LOCK:
        # TODO: check output?
        subprocess.call('r10k', kind, *values)


def consume_queue(kind, queue):
    while True:
        values = {queue.get(True)}

        # Minimise the number of calls to r10k, by grabbing any other items off the queue too
        while True:
            try:
                values.add(queue.get_nowait())
            except Empty:
                break

        run_r10k(kind, values)


t = Thread(target=consume_queue, args=('envs', ENVIRONMENT_QUEUE))
t.start()

t = Thread(target=consume_queue, args=('modules', MODULE_QUEUE))
t.start()
```

It has two threads: one for each queue and consumes it. Then there's a lock around r10k runs. The main benefit is that you use the blocking feature of queues and don't need to enter a busy loop. That removes a lot of other code.

**Comment by dhollinger** [comment]
Queuing support is definitely planned, I just haven't had time to work on it.

**Comment by sebastianrakel** [comment]
i will have a look and will provide a PR with my idea of it :)
