### ISSUE TITLE
Add GoDoc Comments

### ISSUE THREAD

**Issue by dhollinger** [voxpupuli/webhook-go#9]
Add comments to the code in GoDoc format

**Comment by ankush-web-eng** [comment]
Can you assign it to me? Looking to make my a contribution to this project.

**Comment by ankush-web-eng** [comment]
Hey, is it still open? If yes, can you assign it to me.

**Comment by dhollinger** [comment]
Assigned. Thanks! 

I haven't had time to work on this

**Comment by ankush-web-eng** [comment]
I have opened the Pull request for it #177 about a week ago. Please review it and give me feedback if further work needed on it.
